name: Documentation

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0

            - name: Install latest toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  default: true
                  override: true
            - name: Build Docs
              run: cargo doc --color=always
            - name: Copy docs and push
              run: |
                  git config --global user.name 'github-actions[bot]'
                  git config --global user.email 'github-actions[bot]@users.noreply.github.com'
                  git checkout gh-pages

                  rm -rf docs
                  cp -r target/doc ./docs
                  cp index.html docs/

                  git add docs
                  git commit --allow-empty -am  "Auto Generated Documentation"
                  git push
